# Generated by Django 6.0.1 on 2026-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resumeanalysis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='after_text',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='optimized_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
